-- 코드를 입력하세요
SELECT T.WRITER_ID, U.NICKNAME,
                (U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2) AS 전체주소,
                (SUBSTR(U.TLNO,0,3) || '-' || SUBSTR(U.TLNO,4,4) || '-' || SUBSTR(U.TLNO,8,4)) AS 전화번호
FROM(SELECT WRITER_ID, COUNT(WRITER_ID) AS COUNT
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID) T 
        INNER JOIN USED_GOODS_USER U
        ON T.WRITER_ID = U.USER_ID
WHERE COUNT >= 3        
ORDER BY T.WRITER_ID DESC