-- 코드를 입력하세요
-- SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
-- FROM (
--         SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID,
--                 USER_ID, SALES_AMOUNT
--         FROM ONLINE_SALE
--         WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
        
--         UNION
        
--         SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, 
--                     NULL, SALES_AMOUNT
--         FROM OFFLINE_SALE
--         WHERE TO_CHAR(SALES_DATE, 'YYYY-MM-DD') = '2022-03'
-- )
-- ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

-- SELECT
--         TO_CHAR(SALES_DATE,'YYYY-MM-DD') SALES_DATE,
--         PRODUCT_ID,
--         TO_CHAR(USER_ID) AS USER_ID,
--         SALES_AMOUNT
-- FROM
--         ONLINE_SALE
-- WHERE
--         TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-03'

-- UNION

-- SELECT
--         TO_CHAR(SALES_DATE,'YYYY-MM-DD') SALES_DATE,
--         PRODUCT_ID,
--         'NULL' USER_ID,
--         SALES_AMOUNT
-- FROM
--         OFFLINE_SALE
-- WHERE
--         TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-03'
        
-- ORDER BY
--         SALES_DATE, PRODUCT_ID, USER_ID



SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') SALES_DATE, 
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT

FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD') >= '2022-03-01' and TO_CHAR(SALES_DATE,'YYYY-MM-DD') < '2022-04-01'

UNION

SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') SALES_DATE, 
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD') >= '2022-03-01' and TO_CHAR(SALES_DATE,'YYYY-MM-DD') < '2022-04-01'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID