-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE*C.SALES) AS TOTAL_SALES
FROM (BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID)
JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE TO_CHAR(C.SALES_DATE,'YYYY') = 2022 AND TO_CHAR(C.SALES_DATE,'MM') ='01'
GROUP BY A.AUTHOR_ID, A.CATEGORY, B.AUTHOR_NAME
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC