-- 코드를 입력하세요
SELECT DISTINCT RC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR RC LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON RC.CAR_ID = RH.CAR_ID
WHERE RC.CAR_TYPE = '세단' AND TO_CHAR(RH.START_DATE,'MM')='10'
ORDER BY RC.CAR_ID DESC