-- 코드를 입력하세요
-- SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR,
--             COUNT(TO_NUMBER(TO_CHAR(DATETIME,'HH'))) AS COUNT
-- FROM ANIMAL_OUTS
-- GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
-- ORDER BY HOUR

-- SELECT * FROM ANIMAL_OUTS
-- ORDER BY DATETIME

SELECT HOUR, COUNT(O.DATETIME) AS COUNT
FROM
(
    SELECT LEVEL-1 AS HOUR
    FROM DUAL 
    CONNECT BY LEVEL<25
)A 
LEFT JOIN ANIMAL_OUTS O 
ON A.HOUR = TO_CHAR(O.DATETIME,'HH24') 
GROUP BY HOUR 
ORDER BY HOUR