-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (SELECT I.ANIMAL_ID, I.NAME, (O.DATETIME - I.DATETIME) AS TIME
     FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
     ON I.ANIMAL_ID = O.ANIMAL_ID
     WHERE O.DATETIME IS NOT NULL
     ORDER BY TIME DESC)
WHERE ROWNUM < 3