-- 코드를 입력하세요
-- SELECT 'home/grep/src/'||F.BOARD_ID||'/'||F.FILE_ID||F.FILE_NAME||F.FILE_EXT AS FILE_PATH
-- FROM USED_GOODS_BOARD U INNER JOIN USED_GOODS_FILE F ON U.BOARD_ID = F.BOARD_ID
-- WHERE U.VIEWS = (SELECT MAX(VIEWS) AS V FROM USED_GOODS_BOARD)
-- ORDER BY F.FILE_ID DESC

SELECT '/home/grep/src/'||b.BOARD_ID||'/'||FILE_ID||FILE_NAME||FILE_EXT as FILE_PATH
FROM USED_GOODS_BOARD b, USED_GOODS_FILE f
WHERE b.BOARD_ID = f.BOARD_ID
      AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY f.FILE_ID desc;