-- 코드를 입력하세요
-- 2021년에 가입한 전체 회원
-- SELECT COUNT(USER_ID) FROM USER_INFO
-- WHERE TO_CHAR(JOINED,'YYYY') = '2021'

-- SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, TO_CHAR(SALES_DATE,'YYYYMMDD') SALES_DATE, 
-- TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) SALES_DATE_MONTH FROM ONLINE_SALE
-- WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021')
-- ORDER BY SALES_DATE_MONTH

-- 월별 상품 구매한 회원
-- SELECT COUNT(DISTINCT USER_ID),TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) FROM ONLINE_SALE
-- WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021')
-- GROUP BY TO_NUMBER(TO_CHAR(SALES_DATE,'MM'))


-- CODE 1.
-- SELECT A.YEAR, A.MONTH, A.COUNT_USERID, ROUND(A.COUNT_USERID/B.TOTAL_USERID,1) AS PUCHASED_RATIO
-- FROM ( SELECT COUNT(DISTINCT USER_ID) COUNT_USERID,TO_NUMBER(TO_CHAR(SALES_DATE,'YYYY')) YEAR, TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) MONTH
--         FROM ONLINE_SALE
--         WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021')
--         GROUP BY TO_NUMBER(TO_CHAR(SALES_DATE,'YYYY')), TO_NUMBER(TO_CHAR(SALES_DATE,'MM'))
--         ORDER BY TO_NUMBER(TO_CHAR(SALES_DATE,'YYYY')),  TO_NUMBER(TO_CHAR(SALES_DATE,'MM'))
--       ) A ,
--       (SELECT COUNT(USER_ID) TOTAL_USERID FROM USER_INFO WHERE TO_CHAR(JOINED,'YYYY') = '2021') B
-- ORDER BY YEAR, MONTH


-- CODE 2.
SELECT TO_CHAR(SALES_DATE, 'YYYY') as YEAR,
       TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) as MONTH,
       COUNT(DISTINCT(I.USER_ID)) as PUCHASED_USERS,
       ROUND(COUNT(DISTINCT(I.USER_ID)) / 
             (SELECT COUNT(DISTINCT(USER_ID)) 
              FROM USER_INFO
              WHERE TO_CHAR(JOINED, 'YYYY') = '2021')
             ,1) as PUCHASED_RATIO       
FROM USER_INFO I RIGHT JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')
ORDER BY 1, 2