-- 코드를 입력하세요

SELECT A.ID, A.NAME, B.HOST_ID
FROM PLACES A, ( SELECT HOST_ID, COUNT(HOST_ID) FROM PLACES
                 GROUP BY HOST_ID
                 HAVING COUNT(HOST_ID) >= 2) B
WHERE A.HOST_ID = B.HOST_ID
ORDER BY A.ID
                 


-- SELECT ID, NAME, (
--     SELECT HOST_ID
--     FROM ( SELECT HOST_ID, COUNT(HOST_ID) FROM PLACES
--     GROUP BY HOST_ID
--     HAVING COUNT(HOST_ID) >= 2)) AS HOST_ID
-- FROM PLACES



 -- SELECT HOST_ID
 -- FROM ( SELECT HOST_ID, COUNT(HOST_ID) FROM PLACES
 -- GROUP BY HOST_ID
 -- HAVING COUNT(HOST_ID) >= 2)