-- 코드를 입력하세요

SELECT TO_NUMBER(TO_CHAR(START_DATE,'MM')) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE A.CAR_ID IN (
                SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
                GROUP BY CAR_ID
                HAVING COUNT(*) >= 5
        ) 
AND TO_CHAR(START_DATE, 'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY TO_NUMBER(TO_CHAR(START_DATE,'MM')), A.CAR_ID
HAVING count(*) !=  0
ORDER BY MONTH, CAR_ID DESC




-- SELECT TO_NUMBER(TO_CHAR(START_DATE,'MM')) AS MONTH ,CAR_ID, COUNT(CAR_ID) AS RECORDS
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE TO_CHAR(START_DATE,'YYYYMM') >= '202208'
-- AND TO_CHAR(END_DATE,'YYYYMM') <= '202210'
-- GROUP BY TO_CHAR(START_DATE,'MM'),CAR_ID
-- HAVING COUNT(CAR_ID) >= 5
-- ORDER BY MONTH, CAR_ID DESC