-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_PRICE
FROM USED_GOODS_USER A
INNER JOIN (SELECT WRITER_ID, SUM(PRICE) TOTAL_PRICE
            FROM USED_GOODS_BOARD
            WHERE STATUS = 'DONE'
            GROUP BY WRITER_ID
            HAVING SUM(PRICE) >=700000) B
ON A.USER_ID = B.WRITER_ID
ORDER BY TOTAL_PRICE